clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: openjdk:8
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew test build
    - step:
        name: test
        image: openjdk:11
        caches:
          - sonarcloud
        script:
          - ./gradlew sonarqube