clone:
  depth: full
pipelines:

  default:
    - step:
        name: build
        image: openjdk:11
        caches:
          - gradle
          - gradlewrapper
        script:
          - chmod +x gradlew
          - ./gradlew test build sonarqube -Dsonar.login=$SONAR_TOKEN --stacktrace
definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    gradlewrapper: ~/.gradle/wrappe